# Specify where config values (and the schema) come from:
defaults:
- base_schema  # Will use the dataclass schema (and defaults)
- _self_  # Overrides described in this file will be be applied last (take precedence)

seed: 0
dataloader:
  pin_memory: True
  train_batch_size: 128
  eval_batch_size: 128
  persistent_workers: False  # Doesn't make sense to set to True with current implementation
  num_workers: 4
trak:
  projection_dim: 4096  # 4096 in D-TRAK and Journey TRAK for CIFAR10
  latent_diffusion: False
  use_half_precision: True
num_samples_for_loss: 100