defaults:
- base_schema  # Will use the dataclass schema (and defaults)
- _self_  # Overrides described in this file will be be applied last (take precedence)

save_filename: cifar2_lds_influence_ablation_all.pdf
legend_pre: "\\texttt{Target  Measure}"
legend_labels:
- "\\texttt{Loss   Loss }"
- "\\texttt{ELBO   Loss }"
- "\\texttt{ELBO   ELBO }"
- "\\texttt{ELBO   ELBO*}"
- "\\texttt{ELBO*  ELBO }"
- "\\texttt{ELBO*  ELBO*}"
# - "Traj.  Loss "
# - "Traj.  Traj."
measurement_dirs:
- "/srv/shared/outputs/measurements/DatasetType.cifar2/ddpm_samples_loss_measurement"
- "/srv/shared/outputs/measurements/DatasetType.cifar2/ddpm_samples_elbo_measurement"
- "/srv/shared/outputs/measurements/DatasetType.cifar2/ddpm_samples_elbo_measurement"
- "/srv/shared/outputs/measurements/DatasetType.cifar2/ddpm_samples_elbo_measurement"
- "/srv/shared/outputs/measurements/DatasetType.cifar2/ddpm_samples_simpelbo_measurement"
- "/srv/shared/outputs/measurements/DatasetType.cifar2/ddpm_samples_simpelbo_measurement"
# - "/srv/shared/outputs/measurements/DatasetType.cifar2/idx_train-0ddpm_samples_SAMPLING_TRAJECTORY_LOGPROB_measurement"
# - "/srv/shared/outputs/measurements/DatasetType.cifar2/idx_train-0ddpm_samples_SAMPLING_TRAJECTORY_LOGPROB_measurement"
influence_path_format_strings:
- "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_LOSS_125ekfac_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
- "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_LOSS_125ekfac_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
- "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_ELBO_125ekfac_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
- "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_SIMPLIFIED_ELBO_125ekfac_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
- "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_ELBO_125ekfac_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
- "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_SIMPLIFIED_ELBO_125ekfac_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
# - "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_LOSS_125ekfac_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
# - "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_SAMPLING_TRAJECTORY_LOGPROB_125ekfac_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
damping_values_strings: ["1e-11", "1e-10", "1e-9", "1e-8", "1e-7", "1e-6", "1e-5", "1e-4", "1e-3", "1e-2"]
train_model_idxs_path: "/srv/shared/outputs/idxs/DatasetType.cifar2/idx_train.csv"
retrained_model_idxs_dir: "/srv/shared/outputs/idxs/DatasetType.cifar2/retrain"
suptitle: "CIFAR-2 - K-FAC Influence"
color_groups: [0, 0, 1, 2, 1, 2]
linestyle_groups: [0, 1, 1, 1, 2, 2]
