defaults:
- base_schema  # Will use the dataclass schema (and defaults)
- _self_  # Overrides described in this file will be be applied last (take precedence)

save_filename: artbench_lds_trak_ablation.pdf
legend_pre: "\\texttt{Target  Measure Train.Loss}"
legend_labels:
  - "\\texttt{Loss    Loss    Loss}"
  - "\\texttt{Loss    Sq.Norm Sq.Norm (D-TRAK)}"
measurement_dirs:
- "/srv/shared/outputs/measurements/DatasetType.artbench/idx_train-0ddpm_samples_LOSS_measurement"
- "/srv/shared/outputs/measurements/DatasetType.artbench/idx_train-0ddpm_samples_LOSS_measurement"
influence_path_format_strings:
- "/srv/shared/outputs/DatasetType.artbench/idx_train-0/trak_for_ddpm_samples__measure_LOSS_trainloss_LOSS_125measure_125loss__projdim32768_float32_damping{}/scores.npy"
- "/srv/shared/outputs/DatasetType.artbench/idx_train-0/trak_for_ddpm_samples__measure_SQUARE_NORM_trainloss_SQUARE_NORM_125measure_125loss__projdim32768_float32_damping{}/scores.npy"
damping_values_strings: ["1e-6", "1e-5", "1e-4", "1e-3", "1e-2", "1e-1", "1", "1e1", "1e2", "1e3", "1e4", "1e5", "1e6"]
train_model_idxs_path: null
retrained_model_idxs_dir: "/srv/shared/outputs/idxs/DatasetType.artbench/retrain"
suptitle: "ArtBench - TRAK Influence"
color_groups: [0, 1]
dataset: artbench
rescale_damping_by: 0.00002
num_retrained_models: 50