defaults:
  - base_schema # Will use the dataclass schema (and defaults)
  - _self_ # Overrides described in this file will be be applied last (take precedence)

save_filename: artbench_lds_influence_ablation.pdf
legend_labels:
  # - '\texttt{K-FAC }  (Loss)'
  - '\texttt{EK-FAC}  (Loss)'
measurement_dirs:
  - "/srv/shared/outputs/measurements/DatasetType.artbench/idx_train-0ddpm_samples_LOSS_measurement"
  # - "/srv/shared/outputs/measurements/DatasetType.artbench/idx_train-0ddpm_samples_ELBO_measurement"
influence_path_format_strings:
  # - "/srv/shared/outputs/DatasetType.artbench/idx_train-0/fixed_bias_damping_on_main__influence_for_ddpm_samples_LOSS_125kfac_125measurement_125loss__quantize_8bits__damping{}/influence_scores.npy"
  # - "/srv/shared/outputs/DatasetType.artbench/idx_train-0/influence_for_ddpm_samples_LOSS_63ekfac_125measurement_125loss__quantize_8bits__percentage_damping{}/influence_scores.npy"
  - "/srv/shared/outputs/DatasetType.artbench/idx_train-0/influence_for_ddpm_samples_LOSS_63ekfac_125measurement_125loss__quantize_8bits__damping{}/influence_scores.npy"
damping_values_strings:
  ["1e-10", "1e-9", "1e-8", "1e-7", "1e-6", "1e-5", "1e-4", "1e-3", "1e-2"]
train_model_idxs_path: null
retrained_model_idxs_dir: "/srv/shared/outputs/idxs/DatasetType.artbench/retrain"

suptitle: "Artbench - K-FAC Influence"
color_groups: [0]
dataset: artbench
num_retrained_models: 50
