defaults:
  - base_schema # Will use the dataclass schema (and defaults)
  - _self_ # Overrides described in this file will be be applied last (take precedence)

save_filename: cifar2_lds_influence_ablation.pdf
legend_labels:
 - "$\\mathrm{GGN}^\\texttt{loss\ }$ K-FAC-{expand}"
 - "$\\mathrm{GGN}^\\texttt{loss\ }$ K-FAC-{reduce}"
 - "$\\mathrm{GGN}^\\texttt{model}$ K-FAC-{reduce}"
 - "$\\mathrm{GGN}^\\texttt{model}$ K-FAC-{expand}"
 - "$\\mathrm{GGN}^\\texttt{loss\ }$ \\textbf{E}K-FAC-{expand}"
 - "$\\mathrm{GGN}^\\texttt{model}$ \\textbf{E}K-FAC-{reduce}"
 - "$\\mathrm{GGN}^\\texttt{model}$ \\textbf{E}K-FAC-{expand}"
measurement_dirs:
  - "/srv/shared/outputs/measurements/DatasetType.cifar2/ddpm_samples_loss_measurement"
  - "/srv/shared/outputs/measurements/DatasetType.cifar2/ddpm_samples_loss_measurement"
  - "/srv/shared/outputs/measurements/DatasetType.cifar2/ddpm_samples_loss_measurement"
  - "/srv/shared/outputs/measurements/DatasetType.cifar2/ddpm_samples_loss_measurement"
  - "/srv/shared/outputs/measurements/DatasetType.cifar2/ddpm_samples_loss_measurement"
  - "/srv/shared/outputs/measurements/DatasetType.cifar2/ddpm_samples_loss_measurement"
  - "/srv/shared/outputs/measurements/DatasetType.cifar2/ddpm_samples_loss_measurement"
influence_path_format_strings:
 - "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_250kfac_empirical_expand_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
 - "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_250kfac_empirical_reduce_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
 - "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_250kfac_mc_reduce_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
 - "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_250kfac_mc_expand_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
 - "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_125ekfac_empirical_expand_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
 - "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_125ekfac_mc_reduce_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
 - "/srv/shared/outputs/DatasetType.cifar2/idx_train-0/influence_for_ddpm_samples_125ekfac_mc_expand_250measurement_250loss__quantize_8bits_damping{}/influence_scores.npy"
damping_values_strings: ["1e-11", "1e-10", "1e-9", "1e-8", "1e-7", "1e-6", "1e-5", "1e-4", "1e-3", "1e-2"]
train_model_idxs_path: "/srv/shared/outputs/idxs/DatasetType.cifar2/idx_train.csv"
retrained_model_idxs_dir: "/srv/shared/outputs/idxs/DatasetType.cifar2/retrain"
suptitle: "CIFAR-2 - K-FAC Influence Ablation"
color_groups: [0, 1, 2, 3, 4, 5, 6]
linestyle_groups: [0, 0, 1, 1, 2, 2, 3]
